### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by coldlogix**
Hi Matthias,

Please find attached
1. A fix for compiling on the mac, where the iso format is not found
2. A fix to allow klayout to identify and open lasi produced CIF files

Very likely you can cleanup the CIF fix to be more in line with your style.

With kind regards,
Jonathan

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Hi Jonathan, 

Were you able to compile the latest version on OSX?  I'm looking forward to working with 0.25.

Thanks!
Lukas

**Comment by coldlogix** [comment]
Hi Lukas,

I have compiled klayout on OS X in the past, but no, I haven’t gotten 0.25 working just yet.  Unfortunately it exceeded the amount of time I had for it this weekend, but I thought I’d submit the date fix that was the first thing I ran into.

Jonathan

**Comment by klayoutmatthias** [comment]
HI coldlogix,

I have opened a branch for macos build related fixes. kazzz from the forum is supplying me with inputs - one of them was the date issue you found too. But there seem to be other issues as well. Please check this branch and target macos related changes to this one.

Regarding the CIF related changes - please don't mix commits with different scopes. This makes it difficult for me to accept a pull request. I need more information about this particular change. An issue (ticket) which describes the issue will be helpful. Please also attach an example how the LASI-generated file looks like.

Ideally you commit conforms to the coding style the other code uses (i.e. 2 blanks for indent). Plus if possible also add a test case (db/unit_tests/dbCIFReader.cc in this case).

Matthias

**Comment by coldlogix** [comment]
Hi Matthias,

Thanks for the feedback.  It’s my first ever pull request  :)

I’ll see about getting back around to this as soon as I can.

With best regards,
Jonathan

**Comment by klayoutmatthias** [comment]
no worries :-)

this is also the first pull request I have received on GitHub.  
Basically I should add a contributor agreement that includes the  
details. Having no reason to have one, I was simply too lazy :-)

Kind regards,

Matthias



Quoting coldlogix <notifications@github.com>:

> Hi Matthias,
>
> Thanks for the feedback.  It’s my first ever pull request  :)
>
> I’ll see about getting back around to this as soon as I can.
>
> With best regards,
> Jonathan
>
>
>> On Nov 26, 2017, at 2:19 PM, Matthias Köfferlein

**Comment by klayoutmatthias** [comment]
Please take a look at the #28 fix. If you agree I will close this pull request.

**Comment by klayoutmatthias** [comment]
Too much happened now. I guess this issue is solved otherwise.

**Pull request closed without merging**
