### PR TITLE
Update build.yml - enable builds on main branch

### PR DESCRIPTION
**Pull request by thomaslima**
pull requests should be able to access cache from main branch (caching is useless otherwise).

### CODE REVIEW

**Comment by klayoutmatthias** [comment]
Do you have an idea why the operation was cancelled on the GitHub runners? It wasn't me, so maybe it was you?

continuous-integration/jenkins/pr-head is my own one - it's OK that was cancelled.

**Comment by klayoutmatthias** [comment]
I'd merge is there is no reason to hold this PR back.

**Comment by thomaslima** [comment]
Sorry. I cancelled manually because it would have been a waste of resources.

**Comment by klayoutmatthias** [comment]
Very good. I'm in favor of not waisting resources. I'll merge then.

**Pull request merged**
