### PR TITLE
Fixed #704 (DXF reader: rational splines not supported)

### LINKED ISSUE #704: Rational Splines not supported DXF
SPLINE entities are supported, but the spline type (record 70) is ignored. Rationale splines are not reproduced properly. Code 8 is supported so far.

I have a test case for rationale splines now (code 12). But none for the other flags.

image

### PR DESCRIPTION
**Pull request by klayoutmatthias**

### CODE REVIEW

**Comment by lukasc-ubc** [comment]
Interesting! Are Splines accessible as a primitive object in python?


Lukas Chrostowski
Professor, Electrical and Computer Engineering
University of British Columbia
Quantum Matter Institute
Member, College of the Royal Society of Canada
http://www.mina.ubc.ca/lukasc
http://siepic.ubc.ca
https://qmi.ubc.ca/about/directory/lukas-chrostowski

**Comment by klayoutmatthias** [comment]
@lukasc-ubc Excellent idea! And done (awaits merge): https://github.com/KLayout/klayout/pull/706 :)

**Comment by victorliu** [comment]
This does not appear to be fixed. Using KLayout version 0.27.11, and opening the DXF generated with the following script:
```
import math
import ezdxf

dwg = ezdxf.new(dxfversion='AC1015')
ms = dwg.modelspace()

ms.add_circle((0,0), 0.9)
ms.add_circle((0,0), 1.1)

r2 = math.sqrt(0.5)
spline = ms.add_rational_spline([(1, 0), (1, 1), (0, 1)], [1, r2, 1], 2)
spline.dxf.flags = 12

dwg.saveas('klayout_rational_spline_test.dxf')
```
This should produce a quarter circle between the two full circles. Instead, what I see is a non-rational Bezier with all weights 1:
image

**Comment by klayoutmatthias** [comment]
Please create a new issue. This one isn't an issue, but a pull request and it is closed.

**Comment by klayoutmatthias** [comment]
Never mind. I created an issue for this: https://github.com/KLayout/klayout/issues/1173

**Pull request merged**
