### PR TITLE
switch to real pypi

### PR DESCRIPTION
**Pull request by joamatab**

### CODE REVIEW

**Comment by joamatab** [comment]
perfect,

Done!

thank you Thomas,

**Comment by thomaslima** [comment]
@joamatab can you change the target branch from master to 0.27?

**Comment by joamatab** [comment]
yes,

see this PR
https://github.com/KLayout/klayout/pull/1077

**Comment by klayoutmatthias** [comment]
Thanks for this PR.

You don't need to change the target branch. I'll keep that master and 0.27 synchronized myself when merging.

I just like to suggest one enhancement: it's Ok to use real PyPI for releases, but I actually liked having an option to deploy to test PyPI for example for providing preview releases. So my suggestion was to scan for special tags like "v*-preview" in trigger a PyPI-test deployment for those. 

What do you think?

Matthias

P.S: I hate that PyPI even in the test instance does not allow deleting releases :(

**Comment by joamatab** [comment]
it's quite easy to delete PyPi releases, or i usually just make a new one 

image

**Comment by thomaslima** [comment]
@joamatab can you take a stab at duplicating the upload step (one for test and one for real) based on tag name? I'm on mobile for the next 4 days.

You can delete a pypi wheel but can't reupload with the same version. So only the first pypi upload works.

@klayoutmatthias the only silver lining is that the upload step only runs if tests are successful.

**Comment by klayoutmatthias** [comment]
That's perfect - I don't want to upload anything for which the tests are failing :)

@joamatab Yes, you can delete a release but never use the same one again. Previously I ended up with fake ones just because I made some mistake.

BTW: I got a message by @Kazzz-S who is doing the Mac releases. He is no longer able to push to his own fork:

```
~/GitWork/klayout> git push --porcelain --progress origin refs/heads/0.27:refs/heads/0.27
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
failed to push some refs to 'https://github.com/Kazzz-S/klayout.git'
To https://github.com/Kazzz-S/klayout.git
! refs/heads/0.27:refs/heads/0.27 [remote rejected] \
   (refusing to allow an OAuth App to create or update workflow `.github/workflows/build.yml` without `workflow` scope)
Done
'0.27' rejected (non-fast-forward)
```

How can he solve that?

Matthias

**Comment by joamatab** [comment]
okay,

now it always uploads to test_pypi and also uploads to pypi for new releases 

let me know what you think
Joaquin

**Comment by Kazzz-S** [comment]
> That's perfect - I don't want to upload anything for which the tests are failing :)
> 
> @joamatab Yes, you can delete a release but never use the same one again. Previously I ended up with fake ones just because I made some mistake.
> 
> BTW: I got a message by @Kazzz-S who is doing the Mac releases. He is no longer able to push to his own fork:
> 
> ```
> ~/GitWork/klayout> git push --porcelain --progress origin refs/heads/0.27:refs/heads/0.27
> Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
> failed to push some refs to 'https://github.com/Kazzz-S/klayout.git'
> To https://github.com/Kazzz-S/klayout.git
> ! refs/heads/0.27:refs/heads/0.27 [remote rejected] \
>    (refusing to allow an OAuth App to create or update workflow `.github/workflows/build.yml` without `workflow` scope)
> Done
> '0.27' rejected (non-fast-forward)
> ```
> 
> Edit: I understand he needs to generate a new token and make sure workflow scope is enabled, right?
> 
> Matthias

Yes, you are right. I've regenerated a new token enabling the **workflow scope** and set it in my git client tool (SmartGit).
GithubToken

----

In my case, however, I needed to follow the instructions below.

SmartGit2
https://docs.syntevo.com/SmartGit/Latest/GitHub-integration.html#re-setup-oauth

Now, I can push branches to my fork.

I appreciate your help.
Kazzz-S

**Pull request merged**
