### PR TITLE
Introduce a new environment variable "KLAYOUT_INPUT_HTTP_STREAM_PRIVA…

### PR DESCRIPTION
**Pull request by Kazzz-S**
…TE_DATA_TIMEOUT" to control the timeout for XML document fetching

This is my idea to address the issue #1756.

### CODE REVIEW

**Comment by klayoutmatthias** [comment]
HI @Kazzz-S,

thanks for this PR.

It is fine with me to call the variable simply "KLAYOUT_HTTP_TIMEOUT". That is more generic and fits the purpose.

Matthias

**Comment by klayoutmatthias** [comment]
Hi @Kazzz-S,

I hope it's not a problem I created an alternative proposal here: https://github.com/KLayout/klayout/pull/1764

Reason is that there is also the non-Qt, curl-based HTTP(S) implementation and I wanted both to behave the same. The curl version was not thrown an exception in case of timeouts, so I added this too. I also added a test and named the variable "KLAYOUT_HTTP_TIMEOUT".

Maybe you can take a look there.

Thanks,

Matthias

**Comment by Kazzz-S** [comment]
Hi @klayoutmatthias,

Thank you for taking care of the non-Qt case, too.
Of course, the new implementation is OK with me.

Regards,
Kazzz-S

**Comment by Kazzz-S** [comment]
Hi @klayoutmatthias,

I have tested #1764 on macOS, which works fine.

Thank you.
Kazzz-S

**Pull request closed without merging**
