### PR TITLE
WIP: Parametrizing macbuild to make custom installations easier

### PR DESCRIPTION
**Pull request by thomaslima**
The idea is to divide the build script into small routines that don't depend on global variables. This way, we can use the build4mac script even when the folder names don't follow pre-defined patterns. The idea is to automate ruby/python/qt location detection when installing via homebrew.

This is related to #660 .

### CODE REVIEW

**Comment by klayoutmatthias** [comment]
Thanks for this patch.

I have merged it to master as well (beae26ec)

BR,

Matthias

**Comment by thomaslima** [comment]
Oh. The merge came as a surprise. I thought putting WIP in the tittle prevented github from accepting the merge. I was waiting for @Kazzz-S tests but it is no big deal. I suppose we can open new PRs for that.

Btw, if you have a timeline for the 0.26.9 and after, let me know. That will help me plan for whether to target some improvements for .9 or for the next versions.

Thanks
Thomas

**Comment by klayoutmatthias** [comment]
@thomaslima 

Sorry, I missed the WIP part. If you need another PR, that's fine with me.

I plan to release 0.26.9 within the next few days.

Let me know if you want to put in anything particular. I can delay the release.

Thank and best regards,

Matthias

**Comment by thomaslima** [comment]
Well. I would love to fix #660, which would affect the macos builds. I doubt I can do it in the span of a few days though. So we can perhaps leave it for the next version. Can we use github's milestone feature to organize what goes in .9 and what will go in .10?

LG,
Thomas

**Comment by Kazzz-S** [comment]
@klayoutmatthias,

Build testing on Catalina is in progress on 395a6e39.
If I cannot issue a new PR by 11:00 pm YOUR local time on November 26th, please proceed.
I will catch up with the 0.26.9 release later.

Kazzz-S

**Comment by klayoutmatthias** [comment]
@thomaslima Using the milestone feature is a good idea.

I have used the labels ("for 0.26"), but mainly to remind me to port the changes from master to 0.26.

The 0.26.9 isn't urgent and there aren't many features or bugs anyway. I personally can wait a little. Please take your time.

Thanks and best regards,

Matthias

**Comment by klayoutmatthias** [comment]
@thomaslima and @kazzz - thanks for your contributions. Will this issue be fixed with #686? If so, I'd release 0.26.9.

Thanks and best regards,

Matthias

**Comment by thomaslima** [comment]
Hello @klayoutmatthias I think that #686 completes the tests I was hoping to get done. 

I was referring earlier to the issue #660 . I think that issue is important and it will add a very easy way of getting klayout installed on macs, namely via homebrew, which offers maintained, up-to-date installation of qt and python. So I think it is best if we take our time with it and make sure it works properly. I think it can be left for the next version.

**Comment by Kazzz-S** [comment]
Hello,

On Catalina, the build test was successful.
Regarding Homebrew Python, I have installed two versions, namely python@3.8 and python@3.9.
The latter was auto-detected by the "-p HBAuto" option.
So I think @thomaslima  can continue to implement his idea upon this while keeping #660 open.
Meanwhile, I think @klayoutmatthias  can make a maintenance release of 0.26.9 at this point.

Kazzz-S

**Comment by thomaslima** [comment]
@Kazzz-S excellent. I am testing right now. We can continue the conversation in #660 .

**Pull request merged**
